
project_id = "xyfwsmblaayznplurmfa"

[functions.analyze-prompt]
verify_jwt = false

[functions.update-ai-models]
verify_jwt = false

[functions.get-prompt-counts-per-user]
verify_jwt = false

[functions.list-openai-models]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false
