
project_id = "xyfwsmblaayznplurmfa"

[functions.analyze-prompt]
verify_jwt = false

[functions.update-ai-models]
verify_jwt = false

[functions.get-prompt-counts-per-user]
verify_jwt = false

[functions.list-openai-models]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

# Add support for anonymous access to ensure edge functions work even with auth issues
[auth]
enable_anonymous_users = true
disable_signup = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

