
import { Edit } from "lucide-react";
import { Variable, PromptJsonStructure } from "../types";
import { useEffect, useState, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { hasVariablePlaceholders } from "@/utils/promptUtils";

interface FinalPromptDisplayProps {
  finalPrompt: string;
  getProcessedPrompt: () => string;
  variables: Variable[];
  showJson: boolean;
  masterCommand: string;
  handleOpenEditPrompt: () => void;
}

export const FinalPromptDisplay = ({
  finalPrompt,
  getProcessedPrompt,
  variables,
  showJson,
  masterCommand,
  handleOpenEditPrompt
}: FinalPromptDisplayProps) => {
  const [processedPrompt, setProcessedPrompt] = useState("");
  const [promptJson, setPromptJson] = useState<PromptJsonStructure | null>(null);
  const [isLoadingJson, setIsLoadingJson] = useState(false);
  const [jsonGenerated, setJsonGenerated] = useState(false);
  const { toast } = useToast();
  
  const [userId, setUserId] = useState<string | null>(null);
  const [promptId, setPromptId] = useState<string | null>(null);
  
  useEffect(() => {
    const getUserId = async () => {
      const { data } = await supabase.auth.getSession();
      if (data.session?.user) {
        setUserId(data.session.user.id);
      }
    };
    getUserId();
  }, []);
  
  const relevantVariables = Array.isArray(variables) 
    ? variables.filter(v => v && typeof v === 'object' && v?.isRelevant !== false) 
    : [];
  
  const convertPromptToJson = useCallback(async () => {
    if (!finalPrompt || finalPrompt.trim() === "" || jsonGenerated) return;
    
    setIsLoadingJson(true);
    
    try {
      const { data, error } = await supabase.functions.invoke('prompt-to-json', {
        body: {
          prompt: finalPrompt,
          masterCommand,
          userId,
          promptId
        }
      });
      
      if (error) {
        throw new Error(`Error calling prompt-to-json: ${error.message}`);
      }
      
      if (data && data.jsonStructure) {
        setPromptJson(data.jsonStructure);
        setJsonGenerated(true);
        console.log("Prompt JSON structure generated by o3-mini:", data.jsonStructure);
      }
    } catch (error) {
      console.error("Error converting prompt to JSON:", error);
      toast({
        title: "Error generating JSON",
        description: error instanceof Error ? error.message : "Unknown error",
        variant: "destructive"
      });
    } finally {
      setIsLoadingJson(false);
    }
  }, [finalPrompt, masterCommand, toast, userId, promptId, jsonGenerated]);
  
  useEffect(() => {
    if (showJson && !jsonGenerated && !isLoadingJson) {
      convertPromptToJson();
    }
  }, [showJson, finalPrompt, convertPromptToJson, jsonGenerated, isLoadingJson]);
  
  useEffect(() => {
    try {
      if (typeof getProcessedPrompt === 'function') {
        const result = getProcessedPrompt();
        setProcessedPrompt(result || "");
      }
    } catch (error) {
      console.error("Error processing prompt:", error);
      setProcessedPrompt(finalPrompt || "");
    }
  }, [getProcessedPrompt, finalPrompt, variables]);
  
  const escapeRegExp = (string: string = "") => {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  };
  
  const highlightVariablesInText = (text: string) => {
    if (!text || !Array.isArray(relevantVariables) || relevantVariables.length === 0) {
      return text;
    }
    
    let processedText = text;
    
    // First, highlight variable placeholders
    const placeholderPattern = /{{([^}]+)}}/g;
    processedText = processedText.replace(placeholderPattern, (match, name) => {
      return `<span class="unresolved-variable">${match}</span>`;
    });
    
    // Then highlight variables that have values
    relevantVariables.forEach(variable => {
      if (!variable || !variable.name) return;
      
      try {
        if (variable.value) {
          const escapedValue = escapeRegExp(variable.value);
          if (escapedValue.length > 2) { // Only replace if value is substantial
            const valuePattern = new RegExp(`\\b${escapedValue}\\b`, 'g');
            processedText = processedText.replace(valuePattern, 
              `<span class="variable-highlight">${variable.value}</span>`);
          }
        }
      } catch (error) {
        console.error(`Error highlighting variable ${variable.name}:`, error);
      }
    });
    
    return processedText;
  };
  
  const renderProcessedPrompt = () => {
    if (showJson) {
      try {
        if (isLoadingJson) {
          return <div className="text-xs animate-pulse">Generating JSON structure...</div>;
        }
        
        if (promptJson) {
          return (
            <pre className="text-xs font-mono overflow-x-auto">
              {JSON.stringify(promptJson, null, 2)}
            </pre>
          );
        }
        
        return (
          <pre className="text-xs font-mono">
            {JSON.stringify({ 
              prompt: finalPrompt || "", 
              masterCommand: masterCommand || ""
            }, null, 2)}
          </pre>
        );
      } catch (error) {
        console.error("Error rendering JSON:", error);
        return <pre className="text-xs font-mono">Error rendering JSON</pre>;
      }
    }

    try {
      if (!processedPrompt) {
        return <div className="prose prose-sm max-w-none">{finalPrompt || ""}</div>;
      }
      
      const sections = processedPrompt.split(/^(Task:|Persona:|Conditions:|Instructions:)/gm);
      
      let title = "";
      const titleMatch = processedPrompt.match(/\*\*\[(.*?)\]\*\*/);
      if (titleMatch && titleMatch[1]) {
        title = titleMatch[1];
      }
      
      return (
        <div className="prose prose-sm max-w-none">
          {title && (
            <div className="bg-primary/10 p-2 rounded-md mb-4 font-bold text-center">
              {title}
            </div>
          )}
          
          {sections.map((section, index) => {
            if (!section.trim()) return null;
            
            if (["Task:", "Persona:", "Conditions:", "Instructions:"].includes(section)) {
              return (
                <h3 key={index} className="text-primary font-bold mt-4 mb-2">
                  {section}
                </h3>
              );
            }
            
            const paragraphs = section.split('\n\n');
            return (
              <div key={index}>
                {paragraphs.map((paragraph, pIndex) => {
                  if (!paragraph.trim()) return null;
                  
                  // Check if paragraph contains variable placeholders before processing
                  const hasVariables = hasVariablePlaceholders(paragraph) || 
                                       relevantVariables.some(v => v.value && paragraph.includes(v.value));
                  
                  const highlightedContent = hasVariables 
                    ? highlightVariablesInText(paragraph) 
                    : paragraph;
                    
                  return (
                    <p key={`${index}-${pIndex}`} 
                       dangerouslySetInnerHTML={{ __html: highlightedContent }} />
                  );
                })}
              </div>
            );
          })}
        </div>
      );
    } catch (error) {
      console.error("Error rendering processed prompt:", error);
      return <div className="prose prose-sm max-w-none">{finalPrompt || ""}</div>;
    }
  };

  return (
    <div className="relative flex-1 mb-4 overflow-hidden rounded-lg">
      <button 
        onClick={(e) => {
          e.preventDefault();
          try {
            if (typeof handleOpenEditPrompt === 'function') {
              handleOpenEditPrompt();
            }
          } catch (error) {
            console.error("Error opening edit prompt:", error);
          }
        }}
        className="absolute top-2 right-2 z-10 p-2 rounded-full bg-white/80 hover:bg-white transition-colors"
        aria-label="Edit prompt"
      >
        <Edit className="w-4 h-4 text-accent" />
      </button>
      
      <div 
        className="absolute inset-0 bg-gradient-to-br from-accent via-primary-dark to-primary animate-aurora opacity-10"
        style={{ backgroundSize: "400% 400%" }}
      />
      
      <div className="relative h-full p-6 overflow-y-auto">
        <h3 className="text-lg text-accent font-medium mb-2">Final Prompt</h3>
        <div className="whitespace-pre-wrap text-card-foreground">
          {renderProcessedPrompt()}
        </div>
      </div>
      
      <style>
        {`
        .variable-highlight {
          background-color: rgba(51, 254, 166, 0.2);
          border-radius: 2px;
          padding: 0 2px;
          border-bottom: 1px solid rgba(51, 254, 166, 0.5);
        }
        .unresolved-variable {
          background-color: rgba(254, 51, 51, 0.1);
          border-radius: 2px;
          padding: 0 2px;
          border-bottom: 1px dashed rgba(254, 51, 51, 0.5);
        }
        .animate-aurora {
          animation: aurora 15s ease infinite;
        }
        @keyframes aurora {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        `}
      </style>
    </div>
  );
};
